import { sideBarInterFace } from "~/interfaces/global";
const FactoryItems: sideBarInterFace[] = [
  {
    title: "اعلام بار ها",
    icon: "mdi-book-outline",
    children: [
      {
        title: "لیست اعلام بار",
         path: "/panel/factory/orders",

      },
      {
        title: "سوابق اعلام بار ها",
        to: "/orderHistory/list",
      },
    ],
  },
  {
    title: "حواله ها",
    icon: "mdi-file-document",
    children: [
      {
        title: "لیست حواله ها",
        to: "/remittance/list",
      },
      {
        title: "سوابق حواله ها",
        to: "/remittanceHistory/list",
      },
    ],
  },
  {
    name: "home",
    id: 1,
    path: "/panel/factory/dashboard",
    title: "داشبورد",
    icon: "mdi-chart-bar ",
    children: [],
  },
  {
    name: "orders",
    id: 2,
    path: "/panel/factory/orders",
    title: "اعلام بار ",
    icon: "mdi-truck ",
    children: [],
  },
  {
    name: "hall-announcement",
    id: 2,
    path: "/panel/factory/hall-announcement",
    title: "اعلام بار سریع ",
    icon: "mdi-speedometer",
    children: [],
  },
  {
    name: "hall-announcement/log",
    id: 2,
    path: "/panel/factory/hall-announcement",
    title: "سوابق اعلام بار سریع ",
    icon: "mdi-speedometer",
    children: [],
  },
  {
    name: "hall-announcement/log",
    id: 2,
    path: "/panel/factory/hall-announcement",
    title: "پرداخت کرایه",
    icon: "mdi-speedometer",
    children: [],
  },
  {
    name: "hall-announcement/log",
    id: 2,
    path: "/panel/factory/hall-announcement",
    title: "گردش حساب",
    icon: "mdi-speedometer",
    children: [],
  },
  {
    name: "hall-announcement/log",
    id: 2,
    path: "/panel/factory/hall-announcement",
    title: "درخواست های واریز",
    icon: "mdi-speedometer",
    children: [],
  },
  {
    name: "receipts",
    id: 2,
    path: "/panel/factory/receipts",
    title: "سوابق ثبت فیش",
    icon: "mdi-speedometer",
    children: [],
  },
  {
    name: "remittance",
    id: 2,
    path: "/panel/factory/remittance",
    title: "حواله های جاری",
    icon: "mdi-file",
    children: [],
  },
  {
    name: "waybills",
    id: 3,
    path: "/panel/factory/waybills",
    title: "لیست درخواست بارنامه",
    icon: "mdi-file",
    children: [],
  },
  {
    name: "remittanceHistory",
    id: 5,
    path: "/panel/factory/remittanceHistory",
    title: "سوابق حواله",
    icon: "mdi-file-eye-outline",
    children: [],
  },
  {
    name: "orderHistory",
    id: 5,
    path: "/panel/factory/orderHistory",
    title: "سوابق اعلام بار",
    icon: "mdi-file-eye-outline",
    children: [],
  },
  // {
  //   name: "allOrderSystem",
  //   id: 2,
  //   path: "/panel/factory/orders/allOrderSystem",
  //   title: "سالن اعلام بار",
  //   icon: "mdi-file",
  //   children: [
  //     {
  //       name: "remittancefffff",
  //       id: 2,
  //       path: "/panel/factory/remittance",
  //       title: "حواله های جاری",
  //       icon: "mdi-file",
  //     },
  //   ],
  // },
  {
    name: "tracking",
    id: 2,
    path: "/panel/factory/tracking",
    title: "ردیابی ناوگان",
    icon: "mdi-file",
    children: [],
  },
  {
    name: "carslist",
    id: 6,
    path: "/panel/factory/carslist",
    title: "لیست ناوگان",
    icon: "mdi-file",
    children: [],
  },
];
export { FactoryItems };
